version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8087:8087"
    environment:
      - NIFI_WEB_HTTP_PORT=8087
      - TZ=Europe/Paris
    volumes:
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      - sqlserver_driver:/opt/nifi/nifi-current/drivers

volumes:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_content_repository:
  nifi_provenance_repository:
  nifi_conf:
  nifi_state:
  nifi_logs:
  sqlserver_driver: